/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a appadaptor -c MeeGoAppAdaptor com.meego.launcher.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "appadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MeeGoAppAdaptor
 */

MeeGoAppAdaptor::MeeGoAppAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MeeGoAppAdaptor::~MeeGoAppAdaptor()
{
    // destructor
}

void MeeGoAppAdaptor::hide()
{
    // handle method call com.meego.launcher.hide
    QMetaObject::invokeMethod(parent(), "hide");
}

void MeeGoAppAdaptor::raise(const QStringList &cmdline)
{
    // handle method call com.meego.launcher.raise
    QMetaObject::invokeMethod(parent(), "raise", Q_ARG(QStringList, cmdline));
}

